name: testing_client_win64_sdl2

on:
  push:
    branches: [ testing ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        make BUILD_SERVER=0 USE_DISCORD=1
    - name: Setting variables
      id: vars
      shell: bash
      run: |
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=date::$(date +'%Y-%m-%d-%H%M%S')"
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: q3e-urt-win64-${{ steps.vars.outputs.date }}-sdl2
        artifacts: "${{ github.workspace }}/build/release-mingw64-x86_64/*.exe,${{ github.workspace }}/build/release-mingw64-x86_64/*.dll"
        token: ${{ secrets.GITHUB_TOKEN }}
